name: Build CUDD

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        version:
          # - 2.4.2
          # - 2.5.0
          # - 2.5.1
          - 3.0.0
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - name: Build
        run: |
          wget https://github.com/davidkebo/cudd/raw/refs/heads/main/cudd_versions/cudd-${{ matrix.version }}.tar.gz
          tar --strip-components 1 -zxvf cudd-${{ matrix.version }}.tar.gz
          ./configure --prefix=$(pwd)/build
          make install -j$(nproc)
          tar -zcvf build.tar.gz -Cbuild .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            build/*

      - name: Publish Release
        id: publish
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          name: cudd-${{ matrix.version }}
          tag_name: cudd-${{ matrix.version }}
          files: |
            build.tar.gz
          body: |
            cudd-${{ matrix.version }} release

      - name: Attest Release Files
        id: attest
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: |
            build.tar.gz
